### ISSUE TITLE
Doesn't properly detect user mode changes when multiple modes are changed at once

### ISSUE THREAD

**Issue by brycesteinhoff** [phergie/phergie-irc-plugin-react-usermode#2]
changeUserMode method returns early when multiple modes are set at the same time (e.g. /mode #channel +qo UserNick UserNick). Modes array isn't updated. Logs "Missing channel or user, skipping".

**Comment by elazar** [comment]
Hi @brycesteinhoff! Thanks for the issue report. Can you try using [this plugin](https://github.com/Renegade334/phergie-irc-plugin-react-chanmodes/) instead, to see if the issue has been addressed there? It's a contributor fork that's had a lot of things fixed and is actually a lot better. I just haven't gotten around to forking it into our organization yet.

**Comment by brycesteinhoff** [comment]
Oooh, that does look fancy. Will give it a shot. Thanks!
