### ISSUE TITLE
Does this even work anymore?

### ISSUE THREAD

**Issue by FlyveHest** [phergie/phergie-irc-plugin-react-usermode#5]
This might be me missing something in the Phergie documentation, but does this plugin even work anymore?

The example in the readme states that you should be able to grab a plugin instance via $this->userMode = $config['userMode'];

But if I do this in a plugin, the $config variable is just empty.

How do I access this plugin from another plugin?

**Comment by elazar** [comment]
Plugins conventionally accept an associative array containing their configuration via their constructors. In your Phergie PHP configuration file, instantiate the UserMode plugin, then pass that instance as part of the associative configuration array to the plugin that needs it.

``` php
$userMode = new \Phergie\Irc\Plugin\React\UserMode\Plugin;
$otherPlugin = new \My\Plugin([
    'userMode' => $userMode,
]);
```

**Comment by FlyveHest** [comment]
You can do that in the configuration file?
Thats not at all whats stated in the documentation about setting up plugins, but i'll have to give it a try.

**Comment by elazar** [comment]
@FlyveHest To what documentation are you referring. This approach does appear to be documented in the [Usage example](https://github.com/phergie/phergie-irc-plugin-react-usermode#usage), though it could admittedly stand a bit of explication.

**Comment by FlyveHest** [comment]
@elazar I was referring to the Phergie documentation, specifically how you add plugins.

https://www.phergie.org/users/ (Under the Plugins heading)

According to that, you just specify the list of plugins that should be loaded, you never get the actual object back so you could hand it over to another plugin.

Currently I have extended the client, and am working on supplying on overlying data structure for communication of information between plugins.

**Comment by elazar** [comment]
@FlyveHest The conventional way of making plugins communicate is through [custom events](https://www.phergie.org/developers/#custom-events).

**Comment by FlyveHest** [comment]
Yes, I could see that in some of the others, but personally I think that setting up events for a function call like "Does User X have privilege Y on channel Z" or "Is User X on channel Y" to be very cumbersome, even though it does seem to be a bit more streamlined if you use promises (which I have never worked with)

That is such an integral part of IRC communication that, to me, it makes sense having a plugin that exposes this data in a more readily available way.

**Comment by svpernova09** [comment]
@FlyveHest is there anything else needed in this issue? Looks like @elazar answered your questions

**Comment by FlyveHest** [comment]
Not really, no, other than a mention of the different way of instancing the plugin, opposed to whats in the Phergie official docs might be nice.
