### ISSUE TITLE
add support for 7.1

### ISSUE THREAD

**Issue by matthewtrask** [phergie/phergie-irc-plugin-react-usermode#9]
As 7.1 becomes more stable and closer to a release, I feel that it would be awesome to start testing. We need to add 7.1 to travis for both the test suite and `allow_failures`. Once its an official release, we can remove from the `allow_failures`.

**Comment by elstamey** [comment]
@rocketpastsix Was this fixed by #8  ?

**Comment by svpernova09** [comment]
Fixed via 01f77d131c9f314510f07575da4252ff22ea8e6f
